### ISSUE TITLE
Make visible list of slash commands

### ISSUE THREAD

**Issue by SibJusha** [teabeattle/ds-bot#4]
It is highly preferable to have a list of slash commands appeared when someone starts typing `/`. Example is attached 

![mceclip2](https://github.com/teabeattle/ds-bot/assets/70753029/3872f85b-ee8d-4a80-9359-384070357448)

**Comment by teabeattle** [comment]
I have started to implemet this in the Application branch

**Comment by teabeattle** [comment]
Done
